name: newyork_times_clone_starter
description: New York Times app clone

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: OldLondon
      fonts:
        - asset: assets/OldLondon.ttf
    - family: linlibertine_abl
      fonts:
        - asset: fonts/linlibertine_abl.ttf
    - family: linlibertine_dr
      fonts:
        - asset: fonts/linlibertine_dr.ttf